In [1]:
import pandas as pd
dataset = pd.read_csv("finaldata.csv")

In [2]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,7.5,76.459948,2,3,0,0,1,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1
1,7.5,76.459948,2,2,0,0,0,0,0,148.112676,...,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1
2,7.5,76.459948,0,1,0,0,0,0,0,99.000000,...,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1
3,7.5,76.459948,3,1,0,0,0,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1
4,7.5,55.000000,2,0,0,0,0,0,0,148.112676,...,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97.0,70.000000,0,0,0,0,0,0,0,219.000000,...,37.000000,9800.000000,4.400000,0,0,0,1,0,0,1
395,97.0,70.000000,2,0,0,0,0,0,0,220.000000,...,27.000000,8408.191126,4.705597,1,1,0,1,0,1,1
396,98.0,70.000000,2,3,0,0,0,0,0,110.000000,...,26.000000,9200.000000,3.600000,1,1,0,0,0,0,1
397,99.0,90.000000,0,0,0,0,0,0,0,207.000000,...,38.868902,8408.191126,4.705597,1,1,0,1,0,1,1
398,99.0,80.000000,0,0,0,0,0,0,0,100.000000,...,53.000000,8500.000000,4.900000,0,0,0,1,0,0,0

In [3]:
# Handle missing values if any
dataset = dataset.dropna()

# Encode categorical variables if needed
dataset = pd.get_dummies(dataset, drop_first=True)

# Scale numerical features if necessary (optional)
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# dataset[['numerical_column']] = scaler.fit_transform(dataset[['numerical_column']])

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,7.5,76.459948,2,3,0,0,1,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1
1,7.5,76.459948,2,2,0,0,0,0,0,148.112676,...,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1
2,7.5,76.459948,0,1,0,0,0,0,0,99.000000,...,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1
3,7.5,76.459948,3,1,0,0,0,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1
4,7.5,55.000000,2,0,0,0,0,0,0,148.112676,...,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97.0,70.000000,0,0,0,0,0,0,0,219.000000,...,37.000000,9800.000000,4.400000,0,0,0,1,0,0,1
395,97.0,70.000000,2,0,0,0,0,0,0,220.000000,...,27.000000,8408.191126,4.705597,1,1,0,1,0,1,1
396,98.0,70.000000,2,3,0,0,0,0,0,110.000000,...,26.000000,9200.000000,3.600000,1,1,0,0,0,0,1
397,99.0,90.000000,0,0,0,0,0,0,0,207.000000,...,38.868902,8408.191126,4.705597,1,1,0,1,0,1,1
398,99.0,80.000000,0,0,0,0,0,0,0,100.000000,...,53.000000,8500.000000,4.900000,0,0,0,1,0,0,0

In [5]:
# Assuming the output column is the last column, split into X (inputs) and y (output)
X = dataset.iloc[:, 0:24].values
y = dataset.iloc[:, 24].values

In [6]:
X

array([[ 7.5       , 76.45994832,  2.        , ...,  1.        ,
         1.        ,  0.        ],
       [ 7.5       , 76.45994832,  2.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 7.5       , 76.45994832,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [98.        , 70.        ,  2.        , ...,  0.        ,
         0.        ,  0.        ],
       [99.        , 90.        ,  0.        , ...,  1.        ,
         0.        ,  1.        ],
       [99.        , 80.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ]])

In [7]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        selectk_features = fit1.transform(indep_X)
        return selectk_features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
 
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['SVMnl'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['SVMnl'][idex]=accsvmnl[number]
    return dataframe

dataset1=pd.read_csv("finaldata.csv",index_col=None)
df2=dataset1
indep_X=df2.drop('Possible', axis=1)
dep_Y=df2['Possible']
kbest=selectkbest(indep_X,dep_Y,5)       

acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y)   


classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)
    
    
#result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [9]:
accrf

[0.98]

In [10]:
# Evaluate and select the best feature set based on R2 scores
best_feature_index = np.argmax(accrf)
best_feature_set = kbest[best_feature_index]

print(f"Best feature set (SelectKBest): {best_feature_set}")

Best feature set (SelectKBest): [3.00000000e+00 1.48112676e+02 5.74821053e+01 3.88689024e+01
 8.40819113e+03]

In [11]:
import numpy as np

# Example best_feature_set (replace with your actual values)
best_feature_set = [3.00000000e+00, 1.48112676e+02, 5.74821053e+01, 3.88689024e+01, 8.40819113e+03]

# Get indices of features sorted by their scores in descending order
sorted_indices = np.argsort(best_feature_set)[::-1]

# Assuming dataset is your original DataFrame containing feature columns
# Retrieve the top-ranked feature names based on sorted indices
selected_columns = dataset.columns[sorted_indices]

# Print the selected columns
print("Selected column names:")
print(selected_columns)

Selected column names:
Index(['su', 'bp', 'sg', 'al', 'age'], dtype='object')

In [12]:
# Split the data into training and testing sets using the original X and y
X_train, X_test, y_train, y_test = train_test_split(kbest, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=0)

# Define the hyperparameter grid for grid search
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [None, 10, 20],  # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],  # Minimum number of samples required to split a node
    'min_samples_leaf': [1, 2, 4]  # Minimum number of samples required at each leaf node
}

# Initialize GridSearchCV with the classifier and parameter grid
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5)

# Fit the grid search to the training data
grid_search.fit(X_train, y_train)

# Get the best estimator from the grid search
best_rf_classifier = grid_search.best_estimator_

# Make predictions on the test data using the best estimator
y_pred = best_rf_classifier.predict(X_test)

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate the classification report
report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(report)

# Print the best parameters found by grid search
print("\nBest Parameters:")
print(grid_search.best_params_)

Confusion Matrix:
[[38  1]
 [ 0 41]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.99        39
           1       0.98      1.00      0.99        41

    accuracy                           0.99        80
   macro avg       0.99      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80


Best Parameters:
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}

In [15]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\Users\ELCOT\anaconda3\envs\guvi\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ELCOT\anaconda3\envs\guvi\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ELCOT\anaconda3\envs\guvi\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[ 0 39]
 [ 0 41]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        39
           1       0.51      1.00      0.68        41

    accuracy                           0.51        80
   macro avg       0.26      0.50      0.34        80
weighted avg       0.26      0.51      0.35        80